let suggestions = [
    "Lake Macquarie City Council",
    "Berrigan Shire Council",
    "Mid-Coast Council",
    "Fairfield City Council",
    "Inner West Council",
    "Tweed Shire Council",
    "Dungog Shire Council",
    "Bega Valley Shire Council",
    "Nambucca Shire Council",
    "Sutherland Shire Council",
    "Penrith City Council",
    "Federation Council",
    "Eurobodalla Shire Council",
    "Hawkesbury City Council",
    "Kempsey Shire Council",
    "Queanbeyan-Palerang Regional Council",
    "Bayside Council",
    "Blacktown City Council",
    "Liverpool City Council",
    "Central Coast Council",
    "Warrumbungle Shire Council",
    "Shoalhaven City Council",
    "Canterbury-Bankstown Council",
    "Port Stephens Council",
    "Coffs Harbour City Council",
    "Northern Beaches Council",
    "Balranald Shire Council",
    "Clarence Valley Council",
    "Bellingen Shire Council",
    "Liverpool Plains Shire Council",
    "Albury City Council",
    "Byron Shire Council",
    "Wollongong City Council",
    "Tamworth Regional Council",
    "Council of the City of Sydney",
    "The Council of the Shire of Hornsby",
    "City of Parramatta Council",
    "Cumberland Council",
    "Randwick City Council",
    "Ku-ring-gai Council",
    "Georges River Council",
    "Waverley Council",
    "Ryde City Council",
    "Burwood Council",
    "North Sydney Council",
    "Willoughby City Council",
    "The Hills Shire Council",
    "City of Canada Bay Council",
    "Woollahra Municipal Council",
    "The Council of the Municipality of Hunters Hill",
    "Campbelltown City Council",
    "Lane Cove Municipal Council",
    "Mosman Municipal Council",
    "Strathfield Municipal Council",
    "Wagga Wagga City Council",
    "Greater Hume Shire Council",
    "Lockhart Shire Council",
    "Armidale Regional Council",
    "Ballina Shire Council",
    "Richmond Valley Council",
    "Bathurst Regional Council",
    "Oberon Council",
    "Wingecarribee Shire Council",
    "Gwydir Shire Council",
    "Blayney Shire Council",
    "Upper Lachlan Shire Council",
    "Snowy Monaro Regional Council",
    "Bourke Shire Council",
    "Brewarrina Shire Council",
    "Broken Hill City Council",
    "Hilltops Council",
    "Yass Valley Council",
    "Camden Council",
    "Wollondilly Shire Council",
    "Cobar Shire Council",
    "Lachlan Shire Council",
    "Coonamble Shire Council",
    "Gilgandra Shire Council",
    "Cootamundra-Gundagai Regional Council",
    "Cabonne Shire Council",
    "Cowra Shire Council",
    "Murray River Council",
    "Edward River Council",
    "Dubbo Regional Council",
    "Narromine Shire Council",
    "Forbes Shire Council",
    "Glen Innes Severn Council",
    "Goulburn Mulwaree Council",
    "Weddin Shire Council",
    "Upper Hunter Shire Council",
    "Mid-Western Regional Council",
    "Narrabri Shire Council",
    "Gunnedah Shire Council",
    "City of Lithgow Council",
    "Hay Shire Council",
    "Carrathool Shire Council",
    "Inverell Shire Council",
    "Murrumbidgee Council",
    "Coolamon Shire Council",
    "Junee Shire Council",
    "Shellharbour City Council",
    "The Council of the Municipality of Kiama",
    "Lismore City Council",
    "Cessnock City Council",
    "Newcastle City Council",
    "Maitland City Council",
    "Port Macquarie-Hastings Council",
    "Central Darling Shire Council",
    "Moree Plains Shire Council",
    "Muswellbrook Shire Council",
    "Griffith City Council",
    "Leeton Shire Council",
    "Narrandera Shire Council",
    "Bogan Shire Council",
    "Orange City Council",
    "Parkes Shire Council",
    "Blue Mountains City Council",
    "Kyogle Council",
    "Singleton Council",
    "Temora Shire Council",
    "Tenterfield Shire Council",
    "Snowy Valleys Council",
    "Uralla Shire Council",
    "Walcha Council",
    "Walgett Shire Council",
    "Warren Shire Council",
    "Wentworth Shire Council",
    "Bland Shire Council",
    "Unincorporated Far West",
    "Cumberland Council ",
    "Port Macquarie-Hastings",
    "Northern Beaches",
    "Byron",
    "Mid-Coast",
    "Wollongong",
    "Orange",
    "Camden",
    "Snowy Monaro Regional",
    "North Sydney",
    "Sydney",
    "Hawkesbury",
    "Cumberland",
    "Ballina",
    "Bayside",
    "Bega Valley",
    "Fairfield",
    "Randwick",
    "Waverley",
    "Central Coast",
    "Willoughby",
    "Maitland",
    "Liverpool",
    "Sutherland Shire",
    "City Of Parramatta",
    "Hornsby",
    "Goulburn Mulwaree",
    "Canterbury-Bankstown",
    "Bathurst Regional",
    "Shoalhaven",
    "Tweed",
    "Ryde",
    "Hay",
    "Lake Macquarie",
    "Inner West",
    "Kiama",
    "Mid-Western Regional",
    "Kyogle",
    "Singleton",
    "Lane Cove"
]